import mongoose from "mongoose";
import {model} from "mongoose";
const blogSchema = new mongoose.Schema(
    {
        _id:{
            type: Number,
            required: true,
        },
        adminID:{
            type:Number,
            default:0
        },
        langID:{
            type:Number,
            default:1
        },
        title:String,
        titleRewrite:String,
        redirect301: {
            type:String,
        },
        canonical:{
            type:String,
        },
        mail:{
            type:Number,
            default:0,
        },
        picture:{
            type:String,
        },
        teaser:{
            type:String,
        },
        description:{
            type:String,
        },
        thongTin:{
            type:String,
        },
        des:{
            type:String,
        },
        keyword:String,
        video:{
            type:String,
        },
        categoryID:{
            type:Number,
            default:0
        },
        categoryCB:{
            type:Number,
        },
        date:Date,
        adminEdit: {
            type:Number,
            default:0
        },
        dateLastEdit:{
            type:Date,
            default:0
        },
        order:{
            type:Number,
            default:0
        },
        hits:{
            type:Number,
            default:0
        },
        active:{
            type:Number,
            default:1
        },
        cateUrl:{
            type:String,
        },
        hot:{
            type:Number,
            default:0
        },
        new:{
            type:Number,
            default:0
        },
        view:{
            type:Number,
            default:0
        },
        urlLq:{
            type:String,
        },
        tagCate:{
            type:Number,
            default:0,
        },
        Vl:{
            type:String,
        },
        tdgy:{
            type:String,
        },
        ndgy:{
            type:String,
        },
        audio:{
            type:Number,
            default:0
        },
    },
    { collection: 'Blog',  
    versionKey: false , 
    timestamp:true
  })
  export default model("Blog", blogSchema);