import {Schema, model} from "mongoose";

export default interface ISetOfTestBlog{
    name:string,
    redirect301:number,
    title:number,
    url:number,
    cateID:number,
    tagID:string,
    avatar:number,
    pictureWeb:number,
    pictureWeb2:number,
    linkWeb:number,
    teaser:string,
    sapo:number,
    descripption:number,
    view:number,
    time:number,
    dq:string,
    cateUrl:number,
    poinDg:number,
    adminEdit:number,
    audio:number,
}
const setOfTestBlogSchema = new Schema<ISetOfTestBlog>({
    name: {
        type:String,
        required:true,
    },
    redirect301:{
        type:Number,
        required:true,
    },
    title:{
        type:Number,
        required:true,
    },
    url:{
        type:Number,
        required:true,
    },
    cateID:{
        type:Number,
        required:true,
    },
    tagID:{
        type:String,
        required:true,
    },
    avatar:{
        type:Number,
        required:true,
    },
    pictureWeb:{
        type:Number,
        required:true,
    },
    pictureWeb2:{
        type:Number,
        required:true,
    },
    linkWeb:{
        type:Number,
        required:true,
    },
    teaser:{
        type:String,
        required:true,
    },
    sapo:{
        type:Number,
        required:true,
    },
    descripption:{
        type:Number,
        required:true,
    },
    view:{
        type:Number,
        required:true,
    },
    time:{
        type:Number,
        required:true,
    },
    dq:{
        type:String,
        required:true,
    },
    cateUrl:{
        type:Number,
        required:true,
    },
    poinDg:{
        type:Number,
        required:true,
    },
    adminEdit:{
        type:Number,
        required:true,
    },
    audio:{
        type:Number,
        required:true,
        default:0,
    },
})
const SetOfTest = model('Set_Of_Test_Blog', setOfTestBlogSchema);



export { SetOfTest };
