import mongoose from "mongoose";
const setOfTestBlogSchema = new mongoose.Schema(
    {
        _id:{
            type: Number,
            required: true,
        },
        name: {
            type:String,
            required:true,
        },
        redirect301:{
            type:Number,
            required:true,
        },
        title:{
            type:Number,
            required:true,
        },
        url:{
            type:Number,
            required:true,
        },
        cateID:{
            type:Number,
            required:true,
        },
        tagID:{
            type:String,
            required:true,
        },
        avatar:{
            type:Number,
            required:true,
        },
        pictureWeb:{
            type:Number,
            required:true,
        },
        pictureWeb2:{
            type:Number,
            required:true,
        },
        linkWeb:{
            type:Number,
            required:true,
        },
        teaser:{
            type:String,
            required:true,
        },
        sapo:{
            type:Number,
            required:true,
        },
        descripption:{
            type:Number,
            required:true,
        },
        view:{
            type:Number,
            required:true,
        },
        time:{
            type:Number,
            required:true,
        },
        dq:{
            type:String,
            required:true,
        },
        cateUrl:{
            type:Number,
            required:true,
        },
        poinDg:{
            type:Number,
            required:true,
        },
        adminEdit:{
            type:Number,
            required:true,
        },
        audio:{
            type:Number,
            required:true,
            default:0,
        },
    })
